#!/usr/bin/env python3
"""Preserve server_geo across a full re-ingest.

`ingest.py` deletes survey.db and rebuilds it from the git histories, which is
the right way to pick up new commits but takes server_geo with it. Every other
derived table in survey.db can be regenerated by the pipeline; server_geo cannot,
because geo.py needs the db-ip city-lite CSV and that file is not kept in the
repo. Losing it empties the world map and every country chart, silently - the
page still renders, just with 90k servers missing.

So: `save` before a re-ingest, `restore` after. Rows are keyed by server URL
rather than server_id, because ids are assigned in first-appearance order across
all sources and the FOFA/Shodan/live-probe merges renumber on every run - an
id-keyed restore would attach the wrong city to the wrong machine and look fine.

    python3 geo_keep.py save      # before ingest.py
    python3 geo_keep.py restore   # after ingest_snapshot.py
"""
import os, sqlite3, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SURVEY = os.path.join(ROOT, "survey.db")
KEEP = os.path.join(ROOT, "pipeline", "geo_keep.db")

DDL = """CREATE TABLE IF NOT EXISTS geo_by_url(
  url TEXT PRIMARY KEY, continent TEXT, country TEXT,
  stateprov TEXT, city TEXT, lat REAL, lon REAL)"""


def save():
    con = sqlite3.connect(SURVEY)
    if not con.execute("SELECT name FROM sqlite_master WHERE type='table'"
                       " AND name='server_geo'").fetchone():
        print("  no server_geo to save"); return 0
    con.execute(f"ATTACH ? AS k", (KEEP,))
    con.execute(DDL.replace("geo_by_url", "k.geo_by_url"))
    # merge rather than replace: an older save may hold servers a later survey
    # no longer lists, and those placements are still correct.
    con.execute("""INSERT OR REPLACE INTO k.geo_by_url
        SELECT s.url, g.continent, g.country, g.stateprov, g.city, g.lat, g.lon
        FROM server_geo g JOIN server s ON s.id=g.server_id""")
    con.commit()
    n = con.execute("SELECT COUNT(*) FROM k.geo_by_url").fetchone()[0]
    print(f"  geo_keep: {n:,} placements saved")
    con.close(); return 0


def restore():
    if not os.path.exists(KEEP):
        print("  geo_keep.db absent; nothing to restore", file=sys.stderr); return 0
    con = sqlite3.connect(SURVEY)
    con.executescript("""
      CREATE TABLE IF NOT EXISTS server_geo(
        server_id INTEGER PRIMARY KEY, continent TEXT, country TEXT,
        stateprov TEXT, city TEXT, lat REAL, lon REAL);
      CREATE INDEX IF NOT EXISTS server_geo_country ON server_geo(country);
    """)
    con.execute("ATTACH ? AS k", (KEEP,))
    con.execute("""INSERT OR REPLACE INTO server_geo
        SELECT s.id, g.continent, g.country, g.stateprov, g.city, g.lat, g.lon
        FROM k.geo_by_url g JOIN server s ON s.url=g.url""")
    con.commit()
    have, tot = con.execute(
        "SELECT (SELECT COUNT(*) FROM server_geo), (SELECT COUNT(*) FROM server)").fetchone()
    print(f"  geo_keep: {have:,} of {tot:,} servers placed ({100*have/tot:.0f}%)")
    con.close(); return 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "save": sys.exit(save())
    if cmd == "restore": sys.exit(restore())
    print(__doc__); sys.exit(2)
